### ISSUE TITLE
Sometimes some hives disappears on Overview screen. 

### ISSUE THREAD

**Issue by ArmandasRokas** [ArmandasRokas/beeware#68]
```
2020-07-07 07:41:30.713 5858-6115/dk.dtu.group22.beeware I/System.out: Henter URL: http://hivetool.net/db/hive_graph706.pl?chart=Temperature&new_hive_id=240&start_time=2020-07-07+23%3A59%3A59&end_time=2020-07-07+07%3A41%3A59&hive_id=240&number_of_days=0.007951388888888888&last_max_dwdt_lbs_per_hour=30&weight_filter=Raw&max_dwdt_lbs_per_hour=&days=&begin=&end=&units=Metric&undefined=Skip&download_data=Download&download_file_format=csv
2020-07-07 07:41:30.725 5858-6117/dk.dtu.group22.beeware I/System.out: Henter URL: http://hivetool.net/db/hive_graph706.pl?chart=Temperature&new_hive_id=148&start_time=2020-07-07+23%3A59%3A59&end_time=2020-07-07+07%3A41%3A59&hive_id=148&number_of_days=0.007951388888888888&last_max_dwdt_lbs_per_hour=30&weight_filter=Raw&max_dwdt_lbs_per_hour=&days=&begin=&end=&units=Metric&undefined=Skip&download_data=Download&download_file_format=csv
2020-07-07 07:41:34.356 5858-6115/dk.dtu.group22.beeware W/System.err: java.net.SocketTimeoutException: Read timeout
2020-07-07 07:41:34.360 5858-6115/dk.dtu.group22.beeware W/System.err:     at org.jsoup.internal.ConstrainableInputStream.read(ConstrainableInputStream.java:58)
2020-07-07 07:41:34.360 5858-6115/dk.dtu.group22.beeware W/System.err:     at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:287)
2020-07-07 07:41:34.360 5858-6115/dk.dtu.group22.beeware W/System.err:     at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:350)
2020-07-07 07:41:34.360 5858-6115/dk.dtu.group22.beeware W/System.err:     at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:179)
2020-07-07 07:41:34.360 5858-6115/dk.dtu.group22.beeware W/System.err:     at java.io.InputStreamReader.read(InputStreamReader.java:184)
2020-07-07 07:41:34.360 5858-6115/dk.dtu.group22.beeware W/System.err:     at java.io.BufferedReader.fill(BufferedReader.java:172)
2020-07-07 07:41:34.361 5858-6115/dk.dtu.group22.beeware W/System.err:     at java.io.BufferedReader.read1(BufferedReader.java:223)
2020-07-07 07:41:34.361 5858-6115/dk.dtu.group22.beeware W/System.err:     at java.io.BufferedReader.read(BufferedReader.java:297)
2020-07-07 07:41:34.361 5858-6115/dk.dtu.group22.beeware W/System.err:     at java.io.Reader.read(Reader.java:140)
2020-07-07 07:41:34.361 5858-6115/dk.dtu.group22.beeware W/System.err:     at org.jsoup.parser.CharacterReader.bufferUp(CharacterReader.java:58)
2020-07-07 07:41:34.361 5858-6115/dk.dtu.group22.beeware W/System.err:     at org.jsoup.parser.CharacterReader.<init>(CharacterReader.java:35)
2020-07-07 07:41:34.361 5858-6115/dk.dtu.group22.beeware W/System.err:     at org.jsoup.parser.CharacterReader.<init>(CharacterReader.java:43)
2020-07-07 07:41:34.361 5858-6115/dk.dtu.group22.beeware W/System.err:     at org.jsoup.parser.TreeBuilder.initialiseParse(TreeBuilder.java:38)
2020-07-07 07:41:34.361 5858-6115/dk.dtu.group22.beeware W/System.err:     at org.jsoup.parser.HtmlTreeBuilder.initialiseParse(HtmlTreeBuilder.java:65)
2020-07-07 07:41:34.361 5858-6115/dk.dtu.group22.beeware W/System.err:     at org.jsoup.parser.TreeBuilder.parse(TreeBuilder.java:46)
2020-07-07 07:41:34.361 5858-6115/dk.dtu.group22.beeware W/System.err:     at org.jsoup.parser.Parser.parseInput(Parser.java:35)
2020-07-07 07:41:34.361 5858-6115/dk.dtu.group22.beeware W/System.err:     at org.jsoup.helper.DataUtil.parseInputStream(DataUtil.java:169)
2020-07-07 07:41:34.361 5858-6115/dk.dtu.group22.beeware W/System.err:     at org.jsoup.helper.HttpConnection$Response.parse(HttpConnection.java:835)
2020-07-07 07:41:34.361 5858-6115/dk.dtu.group22.beeware W/System.err:     at org.jsoup.helper.HttpConnection.get(HttpConnection.java:285)
2020-07-07 07:41:34.361 5858-6115/dk.dtu.group22.beeware W/System.err:     at dk.dtu.group22.beeware.dal.dao.implementation.WebScraper.getDataLines(WebScraper.java:111)
2020-07-07 07:41:34.361 5858-6115/dk.dtu.group22.beeware W/System.err:     at dk.dtu.group22.beeware.dal.dao.implementation.WebScraper.getHiveMeasurements(WebScraper.java:32)
2020-07-07 07:41:34.361 5858-6115/dk.dtu.group22.beeware W/System.err:     at dk.dtu.group22.beeware.dal.dao.implementation.CachingManager.fetchFromHiveTool(CachingManager.java:121)
2020-07-07 07:41:34.361 5858-6115/dk.dtu.group22.beeware W/System.err:     at dk.dtu.group22.beeware.dal.dao.implementation.CachingManager.updateHive(CachingManager.java:107)
2020-07-07 07:41:34.361 5858-6115/dk.dtu.group22.beeware W/System.err:     at dk.dtu.group22.beeware.dal.dao.implementation.CachingManager.getHive(CachingManager.java:73)
2020-07-07 07:41:34.361 5858-6115/dk.dtu.group22.beeware W/System.err:     at dk.dtu.group22.beeware.business.implementation.Logic.getHive(Logic.java:163)
2020-07-07 07:41:34.361 5858-6115/dk.dtu.group22.beeware W/System.err:     at dk.dtu.group22.beeware.business.implementation.Logic.lambda$getSubscribedHives$0$Logic(Logic.java:128)
2020-07-07 07:41:34.361 5858-6115/dk.dtu.group22.beeware W/System.err:     at dk.dtu.group22.beeware.business.implementation.-$$Lambda$Logic$D5xQuX2j0fqdRPUiR_P1DSTwc_s.run(lambda)
2020-07-07 07:41:34.362 5858-6115/dk.dtu.group22.beeware W/System.err:     at java.lang.Thread.run(Thread
```

**Comment by ArmandasRokas** [comment]
- Logic in line 132 throw new FetchingDataException (extends RuntimeException) . In exception message add hiveId or name, so it can be toasted on the screen.

**Comment by ArmandasRokas** [comment]
Error message: Could not fetch "Stade2" data. Try again later.

**Comment by ArmandasRokas** [comment]
Where to get hivename in Logic?

**Comment by ArmandasRokas** [comment]
Could be related to multiple threads trying to read from the file and throws an exception. Currently, the exception is not handled correctly.

**Comment by ArmandasRokas** [comment]
- these hives should be in chached Arraylist. So maybe there is problem 
- Ok if it cleans chached ArrayList and than should retrieve from file. What about retrieve from file every time. Test if it works slower if it retrieve the hive from file. Or change to SQLlite???  
- Does not make a sense to hold all hives with all data in the RAM. Is it cleaned sometime? Write to Jacob?  
- In overview get hive data from SQLlite with two days. But for the graph get all data 
- In this way it is possible to cache even longer time period and NASA data, because before all the data was storage in RAM (List<Hive>). 
- SQLite vs File
     - https://www.sqlite.org/aff_short.html#:~:text=Reading%20and%20writing%20from%20an,a%20complete%20parse%20in%20memory.
- SQLLite with all fields as in HiveTOOL 

1. Start by findCachedHive(id ) in cachingManager. 
2. Start to receive all hive
3 But then add from to since to now for receiving hive in Overview.
